# HTTP Server
server:
  port: 14568  # HTTP (Tomcat) port

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-preserve-service
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

swagger:
  controllerPackage: preserve.controller

BasicServiceHost: 127.0.0.1
BasicServicePort: 15680
SeatServiceHost: 127.0.0.1
SeatServicePort: 18898
UserServiceHost: 127.0.0.1
UserServicePort: 12342
AssuranceServiceHost: 127.0.0.1
AssuranceServicePort: 18888
StationServiceHost: 127.0.0.1
StationServicePort: 12345
SecurityServiceHost: 127.0.0.1
SecurityServicePort: 11188
TravelServiceHost: 127.0.0.1
TravelServicePort: 12346
ContactsServiceHost: 127.0.0.1
ContactsServicePort: 12347
OrderServiceHost: 127.0.0.1
OrderServicePort: 12031
FoodServiceHost: 127.0.0.1
FoodServicePort: 18856
ConsignServiceHost: 127.0.0.1
ConsignServicePort: 16111
