server:
  port: 18898

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller

OrderServiceHost: 127.0.0.1
OrderServicePort: 12031
OrderOtherServiceHost: 127.0.0.1
OrderOtherServicePort: 12032
ConfigServiceHost: 127.0.0.1
ConfigServicePort: 15679
