server:
  port: 18898

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:127.0.0.1:8848}
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller

OrderServiceHost: ${ORDER_SERVICE_HOST:ts-order-service}
OrderServicePort: ${ORDER_SERVICE_PORT:12031}
OrderOtherServiceHost: ${ORDER_OTHER_SERVICE_HOST:ts-order-other-service}
OrderOtherServicePort: ${ORDER_OTHER_SERVICE_PORT:12032}
ConfigServiceHost: ${CONFIG_SERVICE_HOST:ts-config-service}
ConfigServicePort: ${CONFIG_SERVICE_PORT:15679}
